package com.example.dev22.expandablelistview.databases;


public interface Database {

    String DATABASE_NAME = "db.sqlite";

    Integer DATABASE_VERSION = 2;

    String TABLE_USERS = "USUARIOS",
            FIELD_TABLE_USERS_ID = "ID",
            FIELD_TABLE_USERS_NOME = "NOME",
            FIELD_TABLE_USERS_SOBRENOME = "SOBRENOME",
            FIELD_TABLE_USERS_IDADE = "IDADE";

    String QUERY_CREATE_TABLE_USERS = "CREATE TABLE IF NOT EXISTS " + TABLE_USERS + " (" +
            FIELD_TABLE_USERS_ID + " INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, " +
            FIELD_TABLE_USERS_NOME + " TEXT NOT NULL , " +
            FIELD_TABLE_USERS_SOBRENOME + " TEXT, " +
            FIELD_TABLE_USERS_IDADE + " INTEGER ); ";
    String QUERY_DROP_TABLE_USERS = "DROP TABLE IF EXISTS " + TABLE_USERS;

    String TABLE_ENDERECO = "ENDERECOS",
            FIELD_TABLE_ENDERECO_ID = "ID",
            FIELD_TABLE_ENDERECO_LOCALIZACAO = "ENDERECO",
            FIELD_TABLE_ENDERECO_NUMERO = "NUMERO",
            FIELD_TABLE_ENDERECO_COMPLEMENTO = "COMPLEMENTO",
            FIELD_TABLE_ENDERECO_USERID = "USER_ID";

    String QUERY_CREATE_TABLE_ENDERECO = "CREATE TABLE IF NOT EXISTS " + TABLE_ENDERECO + " (" +
            FIELD_TABLE_ENDERECO_ID + " INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, " +
            FIELD_TABLE_ENDERECO_LOCALIZACAO + " TEXT NOT NULL, " +
            FIELD_TABLE_ENDERECO_NUMERO + " INTEGER, " +
            FIELD_TABLE_ENDERECO_COMPLEMENTO + " TEXT, " +
            FIELD_TABLE_ENDERECO_USERID + " INTEGER , " +
            "FOREIGN KEY(" + FIELD_TABLE_ENDERECO_USERID + ") REFERENCES " + TABLE_USERS +
            "(" + FIELD_TABLE_USERS_ID + ")); ";

    String QUERY_DROP_TABLE_ENDERECO = "DROP TABLE IF EXISTS " + TABLE_ENDERECO;

}
